# Generated by Django 3.0.4 on 2020-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IDnum',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
