# Generated by Django 3.0.4 on 2020-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200326_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SecurityAnswer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='SecurityQuestion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
