# Generated by Django 3.0.4 on 2020-04-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200326_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('browse_search', models.BooleanField()),
                ('borrow', models.BooleanField()),
                ('review', models.BooleanField()),
                ('add', models.BooleanField()),
                ('edit', models.BooleanField()),
                ('delete', models.BooleanField()),
                ('add_instance', models.BooleanField()),
                ('edit_instance', models.BooleanField()),
                ('delete_instance', models.BooleanField()),
                ('create_manager', models.BooleanField()),
                ('view_logs', models.BooleanField()),
                ('any_create', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role'),
        ),
    ]
